# Generated by Django 4.0.10 on 2023-05-13 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='decrition',
            new_name='description',
        ),
    ]
